package com.fcc.domain.mapper;

import com.fcc.domain.model.PlatformUser;
import com.fcc.domain.model.PlatformUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatformUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    long countByExample(PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int deleteByExample(PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int insert(PlatformUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int insertSelective(PlatformUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    List<PlatformUser> selectByExample(PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    PlatformUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlatformUser record, @Param("example") PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlatformUser record, @Param("example") PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformUser record);
}